### ISSUE TITLE
agressive ascii tagging breaks some subsequent readers of unzipped files

### ISSUE THREAD

**Issue by covener** [ZOSOpenTools/unzipport#10]
FYI, here is another one that hit us when /usr/bin/unzip was linked to the port

```
cp /usr/lpp/hzc/lib/libzz.a  testzip/ && \
ls -T testzip/libzz.a && rm -f testzip.zip &&\
/u/WASTST1/zopen-dt/usr/local/bin/zip -r testzip.zip testzip && \
rm -rf testzip && \
/u/WASTST1/zopen-dt/usr/local/bin/unzip -DD -q testzip.zip && \
ls -T testzip/libzz.a 
```

```
- untagged    T=off testzip/libzz.a
t ISO8859-1   T=on  testzip/libzz.a
```

On PLPSC, this broke `cc` being able to read it, I think this is due to honoring the translation implied.
I noticed `md5sum` seems to not disable translation as you might think it would on PLPSC, and it gets the wrong checksum until `chtag -b` is run.

I think this is another example of over-agressive ascii tagging in some of the ports.

**Comment by HarithaIBM** [comment]
In progress!
