### ISSUE TITLE
unzip -a doesn't create ebcdic files

### ISSUE THREAD

**Issue by covener** [ZOSOpenTools/unzipport#13]
Traditional unzip when passed -a creates ebcdic files from ascii source.  It does however create ugly combo of IBM1047 + mixed tag.

ZOT unzip -a just creates ascii-tagged files, defeating the purpose of `-a`, at least relative to the ancient ports.  Presumably this is for non-converting environments or tools.

```
$ rm -rf x; unzip.old -a x.zip; ls -lT x/hello.txt; od -t x1 x/hello.txt
Archive:  x.zip
   creating: x/
 extracting: x/hello.txt             [text]
m IBM-1047    T=off -rw-r--r--   1 COVENER  DEFLT1         6 Jun  4 14:09 x/hello.txt
0000000000    88  85  93  93  96  15
0000000006
COVENER@PLPSC:~ $ rm -rf x; unzip -a x.zip; ls -lT x/hello.txt; od -t x1 x/hello.txt
Archive:  x.zip
   creating: x/
 extracting: x/hello.txt             [text]
t ISO8859-1   T=on  -rw-r--r--   1 COVENER  DEFLT1         6 Jun  4 14:09 x/hello.txt
0000000000    68  65  6C  6C  6F  0A
0000000006
```

**Comment by IgorTodorovskiIBM** [comment]
@covener can you verify if this is now working with the latest version?

**Comment by covener** [comment]
@IgorTodorovskiIBM I upgraded to master.20240604_133728 on my self-maintained zopen install, and the behavior is changed to be closer to the legacy unzip. The file extracted with -a is in EBCDIC but it is not tagged 1047 or even as text.

```
rm -rf x; unzip -a x.zip; ls -lT x/hello.txt; od -t x1 x/hello.txt
Archive:  x.zip
   creating: x/
 extracting: x/hello.txt             [text]
- untagged    T=off -rw-r--r--   1 WASTST1  WASUSER        6 Jun  4 14:09 x/hello.txt
0000000000    88  85  93  93  96  15
0000000006
```

This means e.g. ZOT vim won't open it but non-zot system stuff (/bin/vi or cat) will. I think if ZOT unzip will a2e when it sees `unzip -a` it should also be 1047 and text.

**Comment by HarithaIBM** [comment]
> @IgorTodorovskiIBM I upgraded to master.20240604_133728 on my self-maintained zopen install, and the behavior is changed to be closer to the legacy unzip. The file extracted with -a is in EBCDIC but it is not tagged 1047 or even as text.
> 
> ```
> rm -rf x; unzip -a x.zip; ls -lT x/hello.txt; od -t x1 x/hello.txt
> Archive:  x.zip
>    creating: x/
>  extracting: x/hello.txt             [text]
> - untagged    T=off -rw-r--r--   1 WASTST1  WASUSER        6 Jun  4 14:09 x/hello.txt
> 0000000000    88  85  93  93  96  15
> 0000000006
> ```
> 
> This means e.g. ZOT vim won't open it but non-zot system stuff (/bin/vi or cat) will. I think if ZOT unzip will a2e when it sees `unzip -a` it should also be 1047 and text.

Hey @covener , thank you for testing this. I will check and keep you posted.

**Comment by HarithaIBM** [comment]
Hello @covener I was unable to reproduce this issue. Can you please help me understand the original tag of dir `x`.
If you post `ls -lT` output of `x` it would be helpful for me. Thanks!

**Comment by covener** [comment]
x/ on the filesystem? It gets removed before unpacking the zip so I don't think it can have any effect 

The zip contains just an ascii text file, created on non-zOS.
[x.zip](https://github.com/user-attachments/files/16816073/x.zip)

**Comment by HarithaIBM** [comment]
So, @covener if i have to summarize this - the zip file is created on a non-z/OS system and when you unzip with -a option, on z/OS it is untagged and even text is OFF. Am i understanding the issue correctly?

**Comment by covener** [comment]
That's right:

old freeware unzip: ebcdic contents, ebcdic tag, text=off
old zot unzip: ascii contents, ascii tag, text=on
recent zot unzip: ebcdic contents, no tag, text=off

**Comment by HarithaIBM** [comment]
The issue is fixed as part of https://github.com/zopencommunity/unzipport/pull/16
