### ISSUE TITLE
unzipport can't read archives produced by traditional zip

### ISSUE THREAD

**Issue by covener** [ZOSOpenTools/unzipport#8]
The ancient shareware/tools&toys/whatever zip executable output can't be unzipped by the port, but can be unzipped on distributed systems using the same infozip.

The culprit seems to be that they are marked as IBM1047 and text. `chtag -b` resolves it.

```
t IBM-1047    T=on  testzip.zip
```

**Comment by HarithaIBM** [comment]
Since the z/OS Open tools `zip` file is created in ASCII mode, the content of the `zip` archive is incorrect when tagged as 1047 because it is in binary format. That is why it works correctly when tagged as binary Hence, this is expected and not an issue. Thank you.
